### ISSUE TITLE
Platform icons

### ISSUE THREAD

**Issue by ncannasse** [HeapsIO/heaps.io#22] opened 2018-04-20 20:47 UTC
Platforms icons are messed up on current version, is it normal?
@markknol @deepnight 
![image](https://user-images.githubusercontent.com/1022912/39073052-c2427e0c-44ec-11e8-88d0-25a7789f3caa.png)

**Comment by markknol** [comment] 2018-04-20 21:14
Duplicate of https://github.com/HeapsIO/heaps.io/issues/18

**Comment by markknol** [comment] 2018-04-20 21:14
Its probably because that icon is png, while rest is svg

**Closed as completed by markknol** 2018-04-20 21:14 UTC
